version: '3.7'

services:

  bitcoin-core:
    image: bitcoin
    restart: always
    build: bitcoin
    volumes:
      - "/hdd/bitcoin:/home/bitcoin/.bitcoin"
      - "./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf"
    ports:
      - 8333:8333
#      - 18332:18332
#      - 18333:18333
#      - 18443:18443
#      - 18444:18444
    command: bitcoind -printtoconsole

  notebook:
    image: jupyter/minimal-notebook
    volumes:
      - "./jupyter/requirements.txt:/requirements.txt"
      - "./jupyter/entrypoint.sh:/entrypoint.sh"
      - "./jupyter/data:/home/jovyan/work"
    ports:
      - 8888:8888
    entrypoint: ["/entrypoint.sh"]
    command: ["start-notebook.sh"]

